/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { BuyCreateNestedManyWithoutTokensInput } from "./BuyCreateNestedManyWithoutTokensInput";
import { Type } from "class-transformer";
import { NotificationCreateNestedManyWithoutTokensInput } from "./NotificationCreateNestedManyWithoutTokensInput";
import { SellCreateNestedManyWithoutTokensInput } from "./SellCreateNestedManyWithoutTokensInput";

@InputType()
class TokenCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => BuyCreateNestedManyWithoutTokensInput,
  })
  @ValidateNested()
  @Type(() => BuyCreateNestedManyWithoutTokensInput)
  @IsOptional()
  @Field(() => BuyCreateNestedManyWithoutTokensInput, {
    nullable: true,
  })
  buys?: BuyCreateNestedManyWithoutTokensInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutTokensInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutTokensInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutTokensInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutTokensInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => SellCreateNestedManyWithoutTokensInput,
  })
  @ValidateNested()
  @Type(() => SellCreateNestedManyWithoutTokensInput)
  @IsOptional()
  @Field(() => SellCreateNestedManyWithoutTokensInput, {
    nullable: true,
  })
  sells?: SellCreateNestedManyWithoutTokensInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  symbolField?: string | null;
}

export { TokenCreateInput as TokenCreateInput };
