/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { BuyCreateNestedManyWithoutWalletsInput } from "./BuyCreateNestedManyWithoutWalletsInput";
import { Type } from "class-transformer";
import { SellCreateNestedManyWithoutWalletsInput } from "./SellCreateNestedManyWithoutWalletsInput";
import { TransactionCreateNestedManyWithoutWalletsInput } from "./TransactionCreateNestedManyWithoutWalletsInput";

@InputType()
class WalletCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => BuyCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => BuyCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => BuyCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  buys?: BuyCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  privateKey?: string | null;

  @ApiProperty({
    required: false,
    type: () => SellCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => SellCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => SellCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  sells?: SellCreateNestedManyWithoutWalletsInput;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutWalletsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutWalletsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutWalletsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutWalletsInput;
}

export { WalletCreateInput as WalletCreateInput };
